<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://beangle.github.io/schema/framework"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://beangle.github.io/schema/framework">

  <xs:complexType name="OrmAnnotation">
    <xs:attribute name="class" type="xs:string" use="required"/>
    <xs:attribute name="prefix" type="xs:string" use="required"/>
    <xs:attribute name="schema" type="xs:string"/>
    <xs:attribute name="pluralize" type="xs:boolean"/>
  </xs:complexType>

  <xs:complexType name="OrmProfile">
    <xs:annotation>
      <xs:documentation xml:lang="zh-CN">命名配置，声明类名到表名的处理方式</xs:documentation>
    </xs:annotation>
    <xs:sequence minOccurs="0">
      <xs:element name="annotation" type="OrmAnnotation" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="profile" type="OrmProfile" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="package" type="xs:string" use="required"/>
    <xs:attribute name="pluralize" type="xs:boolean">
      <xs:annotation>
        <xs:documentation xml:lang="zh-CN">是否采用复数化表示，例如user->users</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="schema" type="xs:string"/>
    <xs:attribute name="abbrs" type="xs:string"/>
    <xs:attribute name="prefix" type="xs:string">
      <xs:annotation>
        <xs:documentation xml:lang="zh-CN">表名前缀,可以使用类似sys_,abc_形式</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="Properties">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="prop">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="key" type="xs:string" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="beangle">
    <xs:annotation>
      <xs:documentation><![CDATA[Beangle Framework Config Schema, version 1.0]]></xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:all>
        <xs:element name="web" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="initializer" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="class" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="ems" minOccurs="0">
          <xs:complexType>
            <xs:choice>
              <xs:element name="props" minOccurs="0" type="Properties"/>
              <xs:sequence/>
            </xs:choice>
            <xs:attribute name="app-name" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="cdi" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="module" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="class" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="template" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="freemarker" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="settings" type="Properties"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="jpa" minOccurs="0">
          <xs:annotation>
            <xs:documentation xml:lang="zh-CN">ORM相关配置</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="mapping" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                  <xs:documentation xml:lang="zh-CN">一个继承自org.beangle.data.orm.MappingModule的类名
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="class" type="xs:string" use="required"/>
                  <xs:attribute name="name" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="naming" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="profile" type="OrmProfile" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="mvc" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="static" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="bundle">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="module" minOccurs="0">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string" use="required"/>
                              <xs:attribute name="js" type="xs:string"/>
                              <xs:attribute name="css" type="xs:string"/>
                              <xs:attribute name="depends" type="xs:string"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="version" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="profile" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="action" minOccurs="0">
                      <xs:complexType>
                        <xs:attribute name="suffix" type="xs:string" use="required"/>
                        <xs:attribute name="defaultMethod" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="url" minOccurs="0">
                      <xs:complexType>
                        <xs:attribute name="path" type="xs:string" use="required"/>
                        <xs:attribute name="suffix" type="xs:string" use="required"/>
                        <xs:attribute name="style" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="interceptor" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="decorator" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="package" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>
